trigger:
  - master

jobs:
  - job: macOS_latest
    timeoutInMinutes: 25
    pool:
      vmImage: macOS-latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 16.x
        displayName: "Use node.js 16"
      - script: npm install -g yarn
        displayName: "Install yarn"
      - script: yarn install --frozen-lockfile
        displayName: "yarn install"
      - script: yarn prebuild:upload
        displayName: "upload pre-compiled binary"
