trigger:
  - master

jobs:
  - job: macOS_latest
    timeoutInMinutes: 25
    pool:
      vmImage: macOS-latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 16.x
        displayName: "Use node.js 16"
      - script: npm install -g yarn
        displayName: "Install yarn"
      - script: HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl@3
        displayName: "Install openssl from homebrew"
      - script: yarn install --frozen-lockfile
        displayName: "yarn install"
        env: { OPENSSL_ROOT_DIR: "/usr/local/openssl" }
      - script: yarn prebuild:upload
        displayName: "upload pre-compiled binary"
